version: '3'
services:
  schedule:
    build: ../../Schedule.Jobs/.
    restart: always
    environment:
      - RABBITMQ_URL=amqp://admin:admin@192.168.1.3:5672
  scrap:
    build: ../../Queue.Scrap/.
    restart: always
    environment:
      - RABBITMQ_URL=amqp://admin:admin@192.168.1.3:5672
  generic:
    build: ../../Queue.GenericWorker/.
    restart: always
    environment:
      - RABBITMQ_URL=amqp://admin:admin@192.168.1.3:5672
  openai:
    build: ../../Queue.OpenAI/.
    restart: always
    environment:
      - RABBITMQ_URL=amqp://admin:admin@192.168.1.3:5672
      - OPENAI_API_KEY=
  database:
    build: ../../Queue.Database/.
    restart: always
    environment:
      - RABBITMQ_URL=amqp://admin:admin@192.168.1.3:5672
  assessment:
    build: ../../Api.ResultJobAssessment/.
    restart: always
    environment:
      - CONNECTION_STRING="Server=localhost;Database=devjunior_pro_jobassessment_result;User Id=sa;Password=#Qwerty12345;TrustServerCertificate=true"